### ISSUE TITLE
No such file or directory: 'log_dense_box_bn/infos_dense_box_bn.pkl'

### ISSUE THREAD

**Issue by cuteding** [ruotianluo/Image_Captioning_AI_Challenger#13]
数据和特征都准备好了，但是训练一直报错

read 240000 image features
assigned 220000 images to split train
assigned 10000 images to split val
assigned 10000 images to split test
Traceback (most recent call last):
  File "train.py", line 228, in <module>
    train(opt)
  File "train.py", line 48, in train
    with open(os.path.join(opt.start_from, 'infos_'+opt.id+'.pkl')) as f:
IOError: [Errno 2] No such file or directory: 'log_dense_box_bn/infos_dense_box_bn.pkl'
Terminating BlobFetcher

**Comment by dingdajun** [comment]
已找到解决方案
https://github.com/ruotianluo/ImageCaptioning.pytorch/issues/49

感谢罗博士的帮助！

**Comment by zmskye** [comment]
您好，请问这个问题具体是咋解决的，我遇到了和您一样的问题。我看了你引用的解决方案还是没有理解 @dingdajun

**Comment by danmeng90** [comment]
Have you solved this problem? I encountered the same problem, please help!

**Comment by danmeng90** [comment]
Problem solved! Add --use_box 0 into run_train.sh.

**Comment by mzh1996** [comment]
Sorry to disturb you. @danmeng90 
I still can't solve this problem even if I add --use_box 0 into run_train.sh.
There are two "python train.py " in the run_train.sh file.
I add "--use_box 0"  after both of them.
But it still report the same error.

**Comment by mzh1996** [comment]
> Problem solved! Add --use_box 0 into run_train.sh.
Sorry to disturb you. @danmeng90
I still can't solve this problem even if I add --use_box 0 into run_train.sh.
There are two "python train.py " in the run_train.sh file.
I add "--use_box 0" after both of them.
But it still report the same error.

**Comment by mzh1996** [comment]
> Problem solved! Add --use_box 0 into run_train.sh.

Sorry to disturb you. @danmeng90
I still can't solve this problem even if I add --use_box 0 into run_train.sh.
There are two "python train.py " in the run_train.sh file.
I add "--use_box 0" after both of them.
But it still report the same error.

**Comment by mzh1996** [comment]
> 数据和特征都准备好了，但是训练一直报错
> 
> read 240000 image features
> assigned 220000 images to split train
> assigned 10000 images to split val
> assigned 10000 images to split test
> Traceback (most recent call last):
> File "train.py", line 228, in
> train(opt)
> File "train.py", line 48, in train
> with open(os.path.join(opt.start_from, 'infos_'+opt.id+'.pkl')) as f:
> IOError: [Errno 2] No such file or directory: 'log_dense_box_bn/infos_dense_box_bn.pkl'
> Terminating BlobFetcher

Sorry to disturb you.  @cuteding 
I still can't solve this problem.
Have you solved this problem?

**Comment by danmeng90** [comment]
> > Problem solved! Add --use_box 0 into run_train.sh.
> 
> Sorry to disturb you. @danmeng90
> I still can't solve this problem even if I add --use_box 0 into run_train.sh.
> There are two "python train.py " in the run_train.sh file.
> I add "--use_box 0" after both of them.
> But it still report the same error.

Try to modify "--use_bn 1 --use_box 1" into "--use_bn 0 --use_box 0" in run_train.sh file, which is located in both "python train.py" lines.

**Comment by mzh1996** [comment]
Thank you so much!
Everything gets correct except the meteor evaluation.
I will ignore it.
Thanks again!



---Original---
