### ISSUE TITLE
eval erro

### ISSUE THREAD

**Issue by 18292875242** [ruotianluo/Image_Captioning_AI_Challenger#18]
您好，使用您github上的参数训练模型，在eval时遇到了如下错误：
Traceback (most recent call last):
  File "eval.py", line 137, in <module>
    vars(opt))
  File "/home/dusen/YKQ/Image_Captioning_AI_Challenger/eval_utils.py", line 97, in eval_split
    data['att_masks'][np.arange(loader.batch_size) * loader.seq_per_img]]
KeyError: 'att_masks'
希望能得到您的解答，万分感谢！

**Comment by ruotianluo** [comment]
这段改成，如果原来是none，就设为none

**Comment by ruotianluo** [comment]
那就直接设为none吧

**Comment by 18pxrsun** [comment]
设为none之后又会有其他的问题：
Traceback (most recent call last):
  File "eval.py", line 138, in <module>
    vars(opt))
  File "/home1/ykqHD/master/eval_utils.py", line 102, in eval_split
    seq = model(fc_feats, att_feats,opt=eval_kwargs, mode='sample')[0].data
  File "/home1/public/software/anaconda3/envs/pytorch0.2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home1/ykqHD/master/models/CaptionModel.py", line 31, in forward
    return getattr(self, '_'+mode)(*args, **kwargs)
  File "/home1/ykqHD/master/models/AttModel.py", line 189, in _sample
    return self._sample_beam(fc_feats, att_feats, att_masks, opt)
  File "/home1/ykqHD/master/models/AttModel.py", line 175, in _sample_beam
    self.done_beams[k] = self.beam_search(state, logprobs, tmp_fc_feats, tmp_att_feats, tmp_p_att_feats, tmp_att_masks, opt=opt)
  File "/home1/ykqHD/master/models/CaptionModel.py", line 121, in beam_search
    args = [_.chunk(group_size) for _ in args]
AttributeError: 'NoneType' object has no attribute 'chunk'

**Comment by ruotianluo** [comment]
你去看一下self critical..pytorch，那个里面都fix了基本上

**Comment by 18pxrsun** [comment]
那个里面的eval.py好像没有denseatt:
Traceback (most recent call last):
  File "eval.py", line 102, in <module>
    model = models.setup(opt)
  File "/home1/pxrHD/ImageCaptioning.pytorch-master/models/__init__.py", line 42, in setup
    raise Exception("Caption model not supported: {}".format(opt.caption_model))
Exception: Caption model not supported: denseatt

**Comment by ruotianluo** [comment]
Denseatt should be in self critical pytorch.
