### ISSUE TITLE
TypeError: forward() takes exactly 4 arguments (5 given)

### ISSUE THREAD

**Issue by andrewcao95** [ruotianluo/Image_Captioning_AI_Challenger#23]
Hi Dr. Luo,
When I try to train some model（show tell, show tell attention, att2in.. etc.）using your Image_Captioning_AI_Challenger code, I meet the follwing error.

ps: The model code training of attention mechanism is normal

```shell
DataLoader loading json file:  data/chinese_talk.json
vocab size is  4461
DataLoader loading h5 file:  data/chinese_bu_fc data/chinese_bu_att data/chinese_bu_box data/chinese_talk_label.h5
max sequence length in data is 20
read 240000 image features
assigned 220000 images to split train
assigned 10000 images to split val
assigned 10000 images to split test
Read data: 0.80700802803
Traceback (most recent call last):
  File "train.py", line 241, in <module>
    train(opt)
  File "train.py", line 129, in train
    loss = crit(dp_model(fc_feats, att_feats, labels, att_masks), labels[:, 1:], masks[:, 1:])
  File "/home/andrewcao95/anaconda3/envs/Image_Captioning_AI_Challenger-newest/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/andrewcao95/anaconda3/envs/Image_Captioning_AI_Challenger-newest/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 58, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/andrewcao95/anaconda3/envs/Image_Captioning_AI_Challenger-newest/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes exactly 4 arguments (5 given)
Terminating BlobFetcher

```
I try to debug and find the problem, I find the problem source in https://github.com/ruotianluo/Image_Captioning_AI_Challenger/blob/master/train.py#L125-L130
the parameter `att_masks` is the  reason. 

```python
if not sc_flag:
            loss = crit(dp_model(fc_feats, att_feats, labels, att_masks), labels[:,1:], masks[:,1:])
        else:
            gen_result, sample_logprobs = dp_model(fc_feats, att_feats, att_masks, opt={'sample_max':0}, mode='sample')
            reward = get_self_critical_reward(dp_model, fc_feats, att_feats, att_masks, data, gen_result, opt)
            loss = rl_crit(sample_logprobs, gen_result.data, Variable(torch.from_numpy(reward).float().cuda(), requires_grad=False))
```

Compare with your other project ImageCaptioning.pytorch and self-critical.pytorch 's part, I find you've made a lot of code changes here. But it's hard to modify this part code compare with the new version code. Because I find eval_utils.py and train.py both be modify a lot.

 If I want to use Image_Captioning_AI_Challenger 's code to run those baseline model due to the chinese AI_Challenger dataset. 

How to do the operation with minimum modification cost？

**Comment by ruotianluo** [comment]
What model are you training?

**Comment by ruotianluo** [comment]
The biggest difference for this dataset, is the preprocessing and evaluation. For the preprocessing you can just use what's in this repo, just generate all the files properly. For evaluation, you can reuse the language_eval in this repo. Just remember not feed preds_n into language_eval.

**Comment by andrewcao95** [comment]
Hi Dr.Luo, Thanks for your quick reply. I attempt to train（show tell, show tell attention, att2in.. etc.）those baseline models by using  Image_Captioning_AI_Challenger code.

For your suggestion, I attempt to train model by using  self-critical.pytorch code.  For the preprocessing I use what's in this repo, and for evaluation, I reuse the language_eval in this repo following your step. the modify code in eval_utils.py as follow:

```python
# def language_eval(dataset, preds, preds_n, eval_kwargs, split):
#     model_id = eval_kwargs['id']
#     eval_oracle = eval_kwargs.get('eval_oracle', 0)
#
#     # create output dictionary
#     out = {}
#
#     if len(preds_n) > 0:
#         # vocab size and novel sentences
#         if 'coco' in dataset:
#             dataset_file = 'data/dataset_coco.json'
#         elif 'flickr30k' in dataset or 'f30k' in dataset:
#             dataset_file = 'data/dataset_flickr30k.json'
#         training_sentences = set([' '.join(__['tokens']) for _ in json.load(open(dataset_file))['images'] if not _['split'] in ['val', 'test'] for __ in _['sentences']])
#         generated_sentences = set([_['caption'] for _ in preds_n])
#         novels = generated_sentences - training_sentences
#         out['novel_sentences'] = float(len(novels)) / len(preds_n)
#         tmp = [_.split() for _ in generated_sentences]
#         words = []
#         for _ in tmp:
#             words += _
#         out['vocab_size'] = len(set(words))
#


def language_eval(dataset, preds, eval_kwargs, split):
    model_id = eval_kwargs['id']

    import sys
    sys.path.append("AI_Challenger/Evaluation/caption_eval")
    annFile = 'data/chinese_eval.json'
    from coco_caption.pycxtools.coco import COCO
    from coco_caption.pycxevalcap.eval import COCOEvalCap

    encoder.FLOAT_REPR = lambda o: format(o, '.3f')

    if not os.path.isdir('eval_results'):
        os.mkdir('eval_results')

    #cache_path = os.path.join('eval_results/', model_id + '_' + split + '.json')
    cache_path = os.path.join('eval_results/', '.cache_' + model_id + '_' + split + '.json')


    coco = COCO(annFile)
    valids = coco.getImgIds()
    # filter results to only those in MSCOCO validation set (will be about a third)
    # preds_filt = [p for p in preds if p['image_id'] in valids]
    # print('using %d/%d predictions' % (len(preds_filt), len(preds)))
    json.dump(preds, open(cache_path, 'w'))  # serialize to temporary json file. Sigh, COCO API...

    cocoRes = coco.loadRes(cache_path)
    cocoEval = COCOEvalCap(coco, cocoRes)
    cocoEval.params['image_id'] = cocoRes.getImgIds()
    print(len(set(cocoRes.getImgIds()) & set(coco.getImgIds())))
    cocoEval.evaluate()

    # create output dictionary
    out = {}
    for metric, score in cocoEval.eval.items():
        out[metric] = score

    imgToEval = cocoEval.imgToEval
    # for p in preds:
    #     image_id, caption = p['image_id'], p['caption']
    #     imgToEval[image_id]['caption'] = caption
    with open(cache_path, 'w') as outfile:
        json.dump({'overall': out, 'imgToEval': imgToEval}, outfile)

    return out
```
Then I use this config to try. The training process and the eval=1 process are good. But when I change the caption_model to `adaatt` and other, it shows an error
`RuntimeError: size mismatch, m1: [10 x 0], m2: [2048 x 512] at /tmp/pip-req-build-nP0IoL/aten/src/THC/generic/THCTensorMathBlas.cu:290`

Any suggestion？

```yml
caption_model: newfc
input_json: data/chinese_talk.json
input_fc_dir: data/chinese_bu_fc
input_att_dir: data/chinese_bu_att
input_label_h5: data/chinese_talk_label.h5
learning_rate: 0.0005
learning_rate_decay_start: 0
scheduled_sampling_start: 0
# checkpoint_path: $ckpt_path
# $start_from
language_eval: 1
save_checkpoint_every: 100
val_images_use: 100

batch_size: 10
max_epochs: 30
```

Runtime Error Info:
```shell
DataLoader loading json file:  data/chinese_talk.json
vocab size is  4461
DataLoader loading h5 file:  data/chinese_bu_fc data/chinese_bu_att data/cocotalk_box data/chinese_talk_label.h5
max sequence length in data is 20
read 240000 image features
assigned 220000 images to split train
assigned 10000 images to split val
assigned 10000 images to split test
Read data: 0.0317411422729
Save ckpt on exception ...
model saved to ./log_fc_chinese/model.pth
Save ckpt done.
Traceback (most recent call last):
  File "train.py", line 175, in train
    model_out = dp_lw_model(fc_feats, att_feats, labels, masks, att_masks, data['gts'], torch.arange(0, len(data['gts'])), sc_flag, struc_flag)
  File "/home/andrewcao95/anaconda3/envs/self-critical_newest.pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/andrewcao95/anaconda3/envs/self-critical_newest.pytorch/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/andrewcao95/anaconda3/envs/self-critical_newest.pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/andrewcao95/workspace/self-critical.pytorch/misc/loss_wrapper.py", line 45, in forward
    loss = self.crit(self.model(fc_feats, att_feats, labels, att_masks), labels[:,1:], masks[:,1:])
  File "/home/andrewcao95/anaconda3/envs/self-critical_newest.pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/andrewcao95/workspace/self-critical.pytorch/models/CaptionModel.py", line 32, in forward
    return getattr(self, '_'+mode)(*args, **kwargs)
  File "/home/andrewcao95/workspace/self-critical.pytorch/models/AttModel.py", line 127, in _forward
    p_fc_feats, p_att_feats, pp_att_feats, p_att_masks = self._prepare_feature(fc_feats, att_feats, att_masks)
  File "/home/andrewcao95/workspace/self-critical.pytorch/models/AttModel.py", line 111, in _prepare_feature
    fc_feats = self.fc_embed(fc_feats)
  File "/home/andrewcao95/anaconda3/envs/self-critical_newest.pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/andrewcao95/anaconda3/envs/self-critical_newest.pytorch/lib/python2.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/andrewcao95/anaconda3/envs/self-critical_newest.pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/andrewcao95/anaconda3/envs/self-critical_newest.pytorch/lib/python2.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/andrewcao95/anaconda3/envs/self-critical_newest.pytorch/lib/python2.7/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [10 x 0], m2: [2048 x 512] at /tmp/pip-req-build-nP0IoL/aten/src/THC/generic/THCTensorMathBlas.cu:290

```

**Comment by ruotianluo** [comment]
Sorry, I am not using that one regularly.

Change 

```
def if_use_feat(caption_model):
    # Decide if load attention feature according to caption model
    if caption_model in ['show_tell', 'all_img', 'fc', 'newfc']:
        use_att, use_fc = False, True
    elif caption_model == 'language_model':
        use_att, use_fc = False, False
    elif caption_model in ['updown', 'topdown']:
        use_fc, use_att = True, True
    else:
        use_att, use_fc = True, False
    return use_fc, use_att
```

to 

```
def if_use_feat(caption_model):
    # Decide if load attention feature according to caption model
    if caption_model in ['show_tell', 'all_img', 'fc', 'newfc']:
        use_att, use_fc = False, True
    elif caption_model == 'language_model':
        use_att, use_fc = False, False
    else:
        use_att, use_fc = True, True
    return use_fc, use_att
```

**Comment by andrewcao95** [comment]
Great. It works. All the attention model can be trained.

By the way, How about the classical model show tell and show attention tell ?
I notice that in https://github.com/ruotianluo/self-critical.pytorch/blob/master/models/__init__.py#L18-L21

Some new feature is not support. And I try to train show_tell and get those error as follow:

 If I want to train those show_tell and show_attention_tell model. Such as move OldModel into the model folder. Any suggestion？

Error Info:
```shell
DataLoader loading json file:  data/chinese_talk.json
vocab size is  4461
DataLoader loading h5 file:  data/chinese_bu_fc data/chinese_bu_att data/cocotalk_box data/chinese_talk_label.h5
max sequence length in data is 20
read 240000 image features
assigned 220000 images to split train
assigned 10000 images to split val
assigned 10000 images to split test
Warning: show_tell model is mostly deprecated; many new features are not supported.
/home/andrewcao95/anaconda3/envs/self-critical_newest.pytorch/lib/python2.7/site-packages/torch/nn/modules/rnn.py:51: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
Read data: 8.89301300049e-05
iter 0 (epoch 0), train_loss = 8.408, time/batch = 0.186
Read data: 9.79900360107e-05
iter 1 (epoch 0), train_loss = 8.353, time/batch = 0.032
Read data: 8.98838043213e-05
......
iter 96 (epoch 0), train_loss = 3.840, time/batch = 0.028
Read data: 8.32080841064e-05
iter 97 (epoch 0), train_loss = 3.663, time/batch = 0.028
Read data: 7.39097595215e-05
iter 98 (epoch 0), train_loss = 3.547, time/batch = 0.027
Read data: 0.000292062759399
iter 99 (epoch 0), train_loss = 3.686, time/batch = 0.027
Traceback (most recent call last):
  File "train.py", line 280, in <module>
    train(opt)
  File "train.py", line 234, in train
    dp_model, lw_model.crit, loader, eval_kwargs)
  File "/home/andrewcao95/workspace/self-critical.pytorch/eval_utils.py", line 229, in eval_split
    entropy = - (F.softmax(seq_logprobs, dim=2) * seq_logprobs).sum(2).sum(1) / ((seq>0).float().sum(1)+1)
  File "/home/andrewcao95/anaconda3/envs/self-critical_newest.pytorch/lib/python2.7/site-packages/torch/nn/functional.py", line 1231, in softmax
    ret = input.softmax(dim)
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

```

**Comment by ruotianluo** [comment]
I don't suggest doing that.

**Comment by andrewcao95** [comment]
Yep~. I have try to move OldModel.py into the models folder and attempt the show_attend_tell and all_img. But get TypeError like this repo's error I meet before. 
```shell
  File "/home/andrewcao95/anaconda3/envs/self-critical_newest.pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/andrewcao95/workspace/self-critical.pytorch/misc/loss_wrapper.py", line 45, in forward
    loss = self.crit(self.model(fc_feats, att_feats, labels, att_masks), labels[:,1:], masks[:,1:])
  File "/home/andrewcao95/anaconda3/envs/self-critical_newest.pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes exactly 4 arguments (5 given)
```

Well..Forget about it. If I want to train show tell and show attend tell model for experiment result compare. Any suggestions?
