### ISSUE TITLE
训练时报错ValueError: could not broadcast input array from shape (7,7,2048) into shape (5,7,7)

### ISSUE THREAD

**Issue by chenweize1998** [ruotianluo/Image_Captioning_AI_Challenger#9]
使用python2.7, pytorch 2.1 post2
prepro脚本都已执行。训练时报错
Traceback (most recent call last):
  File "train.py", line 233, in <module>
    train(opt)
  File "train.py", line 118, in train
    data = loader.get_batch('train')
  File "/data/disk1/private/chenweize/concreteness_ch/dataset/Image_Captioning_AI_Challenger/dataloader.py", line 163, in get_batch
    data['att_feats'][i*seq_per_img:(i+1)*seq_per_img, :att_batch[i].shape[0]] = att_batch[i]
ValueError: could not broadcast input array from shape (7,7,2048) into shape (5,7,7)
Terminating BlobFetcher

以及run_train.sh中train的--input_fc_dir与--input_att_dir为data/chinese_bu_fc(att)，其中的bu是否应该为talk？因为没看到生成chinese_bu_fc的文件夹？上面的代码是已经在将bu改为talk后 运行的结果。如果不改，则会报错
Traceback (most recent call last):
  File "train.py", line 233, in <module>
    train(opt)
  File "train.py", line 118, in train
    data = loader.get_batch('train')
  File "/data/disk1/private/chenweize/concreteness_ch/dataset/Image_Captioning_AI_Challenger/dataloader.py", line 135, in get_batch
    ix, tmp_wrapped = self._prefetch_process[split].get()
  File "/data/disk1/private/chenweize/concreteness_ch/dataset/Image_Captioning_AI_Challenger/dataloader.py", line 260, in get
    tmp = self.split_loader.next()
  File "/data/disk1/private/chenweize/concreteness_ch/env/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/data/disk1/private/chenweize/concreteness_ch/env/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IOError: Traceback (most recent call last):
  File "/data/disk1/private/chenweize/concreteness_ch/env/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/data/disk1/private/chenweize/concreteness_ch/dataset/Image_Captioning_AI_Challenger/dataloader.py", line 189, in __getitem__
    att_feat = np.load(os.path.join(self.input_att_dir, str(self.info['images'][ix]['id']) + '.npz'))['feat']
  File "/data/disk1/private/chenweize/concreteness_ch/env/local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 384, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: 'data/chinese_bu_att/74e1bd18c6836e7e0b88e42923f1f7d9a87d9a91.jpg.npz'

**Comment by ruotianluo** [comment]
那是可以下载的

**Comment by chenweize1998** [comment]
> 那是可以下载的

噢我突然明白了...之前一直没想到bu是buttom-up的意思...那这样的话可能我这个问题就和[https://github.com/ruotianluo/Image_Captioning_AI_Challenger/issues/4](url)一样了。但是我还是没太明白您在issue4里的解答

> seq per img不用改。你可以在dataloader的load not时，把14x14x512 reshape成196x512

也就是说seq per img还是5？我这样的话与issue4输出的错误相似，使用resnet101输出的为

> ValueError: could not broadcast input array from shape (7,7,2048) into shape (5,7,7)

即使是将7\*7\*2048 reshape成49*2048也并不对？不知道我的理解是不是哪里有问题？

**Comment by ruotianluo** [comment]
我改了
